### ISSUE TITLE
npm install fails

### ISSUE THREAD

**Issue by dcasegr** [DirtyHairy/node-libxl#12]
It looks like the distribution FTP location is empty and no longer a reliable home for the required libraries.

```
Connecting to ftp://libxl.com...
Connected, receiving directory list...
Failed to identify a suitable download
```

**Comment by SebastienElet** [comment]
I ask to libxl if they plan to bring back the FTP.

Otherwise we will have to use http links / or setup mirrors.

**Comment by jwestbrook** [comment]
You already have a way to get around the problem
```
# export NODE_LIBXL_SDK_ARCHIVE='/usr/src/libxl/libxl-lin-3.7.0.1.tar.gz'
# npm install
```

We just need to update the local archive file when there are updates

**Comment by DirtyHairy** [comment]
Hi all!

Thanks for bringing this to my attention :smiley: I have switched to downloading the latest release via HTTP starting from version 0.2.20 .

Cheers
    -Christian
