### ISSUE TITLE
Build is broken on node 8

### ISSUE THREAD

**Issue by SebastienElet** [DirtyHairy/node-libxl#21]
Hello,

I upgraded to the latest version to be able to use libxl on node 10 but i have few build on node 8 and it's broken.
I will provide a stack trace asap.

**Comment by DirtyHairy** [comment]
Please post a build log - it builds on Travis 😉

**Comment by SebastienElet** [comment]
@DirtyHairy i created a gist with the dockerfile & logs to reproduce the issue : https://gist.github.com/SebastienElet/388191e2f2c05d4d7aaaa79ebb094182

I did some tests and the issue disappear with node 8.12.0 then i think we should not fix the build but only forbid version 8 lower than 8.12 (or lower but we need to do more tests) like in this example : https://github.com/eslint/eslint/blob/d3f3994294cd3eea07b36a52287d59f11929fa72/package.json#L126

**Comment by DirtyHairy** [comment]
Indeed, seems that node 8.9.0 has breaking changes in V8... WTF 😏 I have adjusted the corresponding `#ifdef`s to build properly on 8.9.0 and before. Published as 0.3.2...

**Comment by SebastienElet** [comment]
Awesome, thanks a lot @DirtyHairy !
