### ISSUE TITLE
Build is broken on node 12

### ISSUE THREAD

**Issue by SebastienElet** [DirtyHairy/node-libxl#22]
Hello,

I tried to install LibXL on node 12 but it fails.

I created a gist to reproduce the issue with docker here : https://gist.github.com/SebastienElet/b248cfcae98805d4770244ab0f0dafc4

I will take a look at the source code to see if I may create a PR to fix it

**Comment by DirtyHairy** [comment]
Thanks for the issue. I guess it is time to adapt to V8 API changes again 😏 If you can come up with a PR, I'll be more than happy (I am currently rather swamped), but I'll also try to take a look at it myself.

**Comment by DirtyHairy** [comment]
I have just release version 0.4.0 on NPM. This fixes the build on node 12, but sacrifices support for node < 10 ;)

**Comment by SebastienElet** [comment]
You was faster than me, thanks a lot @DirtyHairy !

**Comment by DirtyHairy** [comment]
It wasn't hard, just tedious, and I've been through that trial of tears before 😏 I hope you didn't invest too much time into your own stab at fixing the build, I would hate to having rendered your work and time useless.
