### ISSUE TITLE
can you upgrade nan to 2?

### ISSUE THREAD

**Issue by aledbf** [DirtyHairy/node-libxl#6]
I tried to use this gist https://gist.github.com/thlorenz/7e9d8ad15566c99fd116 but it requires additional changes.

(I'm trying to update to io.js 3)
Thanks

**Comment by DirtyHairy** [comment]
Hi Manuel!

Thanks for pointing me to the version bump The changes were indeed a royal pita. I have released the update as version 0.2.16; io.js 3.2 is now supported.

**Comment by aledbf** [comment]
@DirtyHairy awesome. 
Thanks!
