### ISSUE TITLE
MD5 packages is deprecated

### ISSUE THREAD

**Issue by lukas-zech-software** [DirtyHairy/node-libxl#7]
The MD5 (uppercase) NPM packages was marked deprecated and should be replaced with md5 >= 2.0

For details see: https://www.npmjs.com/package/MD5

This currently leads to the following problem on ´npm install´ for me, as it tries to install the lowercase package which does not provide a compatible version

```
npm ERR! notarget No compatible version found: md5@'>=1.2.1 <1.3.0'
npm ERR! notarget Valid install targets:
npm ERR! notarget ["1.0.1","1.0.0","2.0.0"]
npm ERR! notarget
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of 'libxl'
```

**Comment by DirtyHairy** [comment]
Thanks for the pointer, I have published a dependency version bump as 0.2.17, including the shift from MD5 to md5.

However, what you describe should not happend (and neither could I reproduce it) --- the upper case version is still available on NPM and can be installed without issues. Out of curiousity: what OS and what version of NPM are you using?

**Comment by lukas-zech-software** [comment]
Thanks for the fast feedback!

I'm running OS X 10.10.5 and NPM  2.12.1

I suspect the problem originates either from ExtFAT on OS X being case insensitive or from NPM.

One other dependency in my project uses the md5 (lowercase) package and it seems that after that one was parsed by NPM the dependency in libxl is also treated as the lowercase package
If I remove the package with the lowercase dependency, the uppercase packages gets installed @1.2.1 without problem

**Comment by DirtyHairy** [comment]
Yeah, that's about what I was suspecting --- sounds like a NPM bug triggered by the case-insensitive file system and the dependency on both MD5 and md5 in separate subprojects.
